name: 'ci'

on:
  push:
    branches:
    - main

jobs:
  deploy-secrets:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - 
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
      - 
        name: Deploy Secrets
        run: go run main.go